$ErrorActionPreference = 'Stop'
$reelRoot = Split-Path $PSScriptRoot -Parent
$reelRuntime = Join-Path $reelRoot 'build/runtime'
$reelCache = Join-Path $reelRoot 'build/downloads'
New-Item -ItemType Directory -Force -Path $reelRuntime,$reelCache | Out-Null

function Get-ReelFile($Uri, $Name, $Sha256) {
    $reelTarget = Join-Path $reelCache $Name
    if (Test-Path -LiteralPath $reelTarget) {
        $reelActual = (Get-FileHash -LiteralPath $reelTarget -Algorithm SHA256).Hash
        if ($reelActual -ne $Sha256) {
            Remove-Item -LiteralPath $reelTarget -Force
        }
    }
    if (-not (Test-Path -LiteralPath $reelTarget)) {
        Write-Host "Downloading $Name"
        $reelPartial = "$reelTarget.partial"
        Remove-Item -LiteralPath $reelPartial -Force -ErrorAction SilentlyContinue
        try {
            Invoke-WebRequest -Uri $Uri -OutFile $reelPartial
            $reelActual = (Get-FileHash -LiteralPath $reelPartial -Algorithm SHA256).Hash
            if ($reelActual -ne $Sha256) { throw "Checksum verification failed for $Name." }
            Move-Item -LiteralPath $reelPartial -Destination $reelTarget -Force
        } finally {
            Remove-Item -LiteralPath $reelPartial -Force -ErrorAction SilentlyContinue
        }
    }
    return $reelTarget
}

$reelPythonZip = Get-ReelFile 'https://www.python.org/ftp/python/3.13.13/python-3.13.13-embed-amd64.zip' 'python-3.13.13.zip' '8766A8775746235E23CF5AEE5027AB1060BB981D93110577ADCF3508AA0CBD55'
$reelPythonDir = Join-Path $reelRuntime 'python'
if (-not (Test-Path "$reelPythonDir/python.exe")) {
    Expand-Archive -LiteralPath $reelPythonZip -DestinationPath $reelPythonDir -Force
}
# Relative search paths make this interpreter relocatable after installation.
Set-Content -LiteralPath "$reelPythonDir/python313._pth" -Encoding ASCII -Value "python313.zip`n.`nLib/site-packages`nimport site"
$reelPip = Get-ReelFile 'https://bootstrap.pypa.io/get-pip.py' 'get-pip.py' 'FB24E693BAB954209A063D90953621412CCAD4A500905A726286E038F508DDF6'
& "$reelPythonDir/python.exe" $reelPip --disable-pip-version-check
if ($LASTEXITCODE -ne 0) { throw 'Could not bootstrap bundled pip.' }
& "$reelPythonDir/python.exe" -m pip install --isolated --disable-pip-version-check --no-input --only-binary=:all: --index-url https://pypi.org/simple -r "$reelRoot/requirements.txt"
if ($LASTEXITCODE -ne 0) { throw 'Could not prepare backend dependencies.' }
# pip-generated bytecode and command wrappers contain the build machine's full path.
# ReelSave invokes modules through python.exe, so neither is required at runtime.
Get-ChildItem -LiteralPath $reelPythonDir -Directory -Filter '__pycache__' -Recurse | Remove-Item -Recurse -Force
Get-ChildItem -LiteralPath $reelPythonDir -File -Filter '*.pyc' -Recurse | Remove-Item -Force
Remove-Item -LiteralPath (Join-Path $reelPythonDir 'Scripts') -Recurse -Force -ErrorAction SilentlyContinue

$reelNodeZip = Get-ReelFile 'https://nodejs.org/dist/v22.23.0/node-v22.23.0-win-x64.zip' 'node-v22.23.0.zip' '425A5BD68CC95E8EB16BCCCD0A75081B48983FC6A26F67126BD4D6C7198231E8'
$reelNodeExtract = Join-Path $reelCache 'node'
Remove-Item -LiteralPath $reelNodeExtract -Recurse -Force -ErrorAction SilentlyContinue
Expand-Archive -LiteralPath $reelNodeZip -DestinationPath $reelNodeExtract -Force
New-Item -ItemType Directory -Force -Path "$reelRuntime/bin", "$reelRuntime/licenses" | Out-Null
Copy-Item -LiteralPath "$reelCache/node/node-v22.23.0-win-x64/node.exe" -Destination "$reelRuntime/bin/node.exe"
Copy-Item -LiteralPath "$reelCache/node/node-v22.23.0-win-x64/LICENSE" -Destination "$reelRuntime/licenses/NODE-LICENSE.txt"

$reelFfmpegZip = Get-ReelFile 'https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip' 'ffmpeg-essentials.zip' '60F467265B1E312373DBCD92200C2618A74850F98D3D078E94296BB3FA2047BA'
$reelFfmpegExtract = Join-Path $reelCache 'ffmpeg'
Remove-Item -LiteralPath $reelFfmpegExtract -Recurse -Force -ErrorAction SilentlyContinue
Expand-Archive -LiteralPath $reelFfmpegZip -DestinationPath $reelFfmpegExtract -Force
$reelFfmpegDir = Get-ChildItem $reelFfmpegExtract -Directory | Select-Object -First 1
Copy-Item -LiteralPath "$($reelFfmpegDir.FullName)/bin/ffmpeg.exe", "$($reelFfmpegDir.FullName)/bin/ffprobe.exe" -Destination "$reelRuntime/bin"
Copy-Item -LiteralPath "$($reelFfmpegDir.FullName)/LICENSE" -Destination "$reelRuntime/licenses/FFMPEG-LICENSE.txt"
Copy-Item -LiteralPath "$reelPythonDir/LICENSE.txt" -Destination "$reelRuntime/licenses/PYTHON-LICENSE.txt"
Set-Content -LiteralPath "$reelRuntime/licenses/SOURCES.txt" -Value @'
Python: https://www.python.org/downloads/release/python-31313/
Node.js: https://nodejs.org/dist/v22.23.0/
FFmpeg Windows builds: https://www.gyan.dev/ffmpeg/builds/
FFmpeg source: https://ffmpeg.org/download.html
yt-dlp: https://github.com/yt-dlp/yt-dlp (Unlicense)
Python package licenses are included in python/Lib/site-packages/*.dist-info.
Electron: https://github.com/electron/electron (MIT; Chromium third-party notices included).
'@
Write-Host 'Bundled Python, yt-dlp, Node and FFmpeg are ready.'
